services:
  scraper:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      sh -c "python manage.py wait_for_db &&
             python scraper/run_daily_scraper.py"
    depends_on:
      - db
    working_dir: /app

  web:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    working_dir: /app

  db:
    image: postgres:16.0-alpine3.17
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - my_db:/var/lib/postgresql/data

volumes:
  my_db:
