# Generated by Django 5.2.3 on 2025-06-29 07:47

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(db_index=True, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("price_usd", models.PositiveIntegerField()),
                ("odometer", models.PositiveIntegerField()),
                ("username", models.CharField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=12,
                        validators=[utils.validators.validate_formatted_phone],
                    ),
                ),
                ("image_url", models.URLField()),
                ("images_count", models.PositiveIntegerField()),
                ("car_number", models.CharField(blank=True, max_length=20, null=True)),
                ("car_vin", models.CharField(blank=True, max_length=50, null=True)),
                ("datetime_found", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-datetime_found"],
            },
        ),
    ]
